# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bcms_feeds}
  s.version = "1.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jon Leighton"]
  s.date = %q{2011-01-13}
  s.description = %q{A BrowserCMS module which fetches, caches and displays RSS/Atom feeds}
  s.email = %q{j@jonathanleighton.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "app/controllers/application_controller.rb",
    "app/helpers/application_helper.rb",
    "app/models/feed.rb",
    "app/portlets/feed_portlet.rb",
    "app/views/portlets/feed/_form.html.erb",
    "app/views/portlets/feed/render.html.erb",
    "db/migrate/20090813213104_add_feeds.rb",
    "db/migrate/20100115202209_modify_feeds_table_to_use_mediumtext.rb",
    "lib/bcms_feeds.rb",
    "lib/bcms_feeds/routes.rb",
    "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/jonleighton/bcms_feeds}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Feeds in BrowserCMS}
  s.test_files = [
    "test/performance/browsing_test.rb",
    "test/test_helper.rb",
    "test/unit/feed_test.rb",
    "test/unit/portlets/feed_portlet_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<simple-rss>, [">= 0"])
    else
      s.add_dependency(%q<simple-rss>, [">= 0"])
    end
  else
    s.add_dependency(%q<simple-rss>, [">= 0"])
  end
end

